name: Dependency Review

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Dependency review
        uses: actions/dependency-review-action@v4
